name: "Import Images"
run-name: ${{ github.actor }} is Import Images 🚀

on:
  pull_request:
    branches:
    - main
    paths:
    - .github/workflows/import-image.yml
    types:
    - opened
    - reopened
    - synchronize
    - closed

jobs:
    scan-docker-image:
      name: "Scan Docker Image with Trivy"
      runs-on: ubuntu-latest
      permissions:
        security-events: write
        contents: read
        actions: read

      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
      
        - name: Check trivyignore
          run: |
            if [ -f trivy/.trivyignore ]; then
              echo "trivyignore file found"
            else
              echo "trivyignore file not found"
            fi
            

        - name: Run Trivy vulnerability scanner for a Docker image
          id: trivy
          uses: aquasecurity/trivy-action@0.24.0
          with:
            image-ref: 'buffdeveloper/vuln-test-image:1.0'
            format: 'sarif'
            ignore-unfixed: true # ignore vulnerabilities that have no fix
            severity: 'CRITICAL,HIGH'
            scanners: 'vuln'
            exit-code: '0'
            output: 'trivy-results.sarif'
            trivyignores: 'trivy/.trivyignore'
          
        - name: Fail if vulnerabilities found
          if: ${{ steps.trivy.outputs.exit-code == '0' }}
          run: |
            cat trivy-results.sarif
            if grep -q '"severity": "HIGH"' trivy-results.sarif || grep -q '"severity": "CRITICAL"' trivy-results.sarif; then
            echo "High or critical vulnerabilities found."
            exit 1
            else
              echo "No high or critical vulnerabilities found."
            fi

        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v3
          if: always()
          with:
            sarif_file: 'trivy-results.sarif'
            category: 'Container Scanning'


        - name: Import image to Azure Container Registry
          run: |
           echo "Image will be imported to Azure Container Registry"