name: "Import Images"
run-name: ${{ github.actor }} is Import Images 🚀

on:
  pull_request:
    branches:
    - main
    paths:
    - .github/workflows/import-image.yml
    types:
    - opened
    - reopened
    - synchronize
    - closed

jobs:
    scan-docker-image:
      name: "Scan Docker Image with Trivy"
      runs-on: ubuntu-latest
      permissions:
        security-events: write
        contents: read
        actions: read

      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
      
        - name: Run Trivy vulnerability scanner for a Docker image
          id: trivy
          uses: aquasecurity/trivy-action@0.24.0
          with:
            image-ref: 'tomcat:9.0.90-jdk17-corretto'
            format: 'sarif'
            exit-code: '0'
            ignore-unfixed: true # ignore vulnerabilities that have no fix
            severity: 'CRITICAL,HIGH'
            trivy-config: 'trivy.yaml'
            output: 'trivy-results.sarif'

        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v3
          if: always()
          with:
            sarif_file: 'trivy-results.sarif'

        - name: Fail if vulnerabilities found
          if: ${{ steps.trivy.outputs.exit-code == '0' }}
          run: |
            echo "This image cannot be imported given the vulnerabilities found"
            exit 1