name: Deploy NGINX Helm Chart
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.event.pull_request.number }} is running

on:
  pull_request:
    branches:
    - main
    types: [opened, synchronize, reopened, closed]

env:
  configuration_item: 'nginx'

jobs:
  deploy:
    name: Deploy NGINX Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: nginx-action

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4

      - name: Fetch Changes
        run: |
          git fetch --all
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} #> nginx-action/files_with_changes
        shell: bash
      
      - name: Check for changed files
        uses: buffdeveloper/nginx-actions/.github/actions/detect-changes@feat/upgrade
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMON_PATH: 'common'
          ENV_PATH: 'env'
          REPO_PATH: 'nginx-action'

      - name: List files with changes
        run: |
          ls -l nginx-action/files_with_changes
        shell: bash

      - name: Check for deleted files
        uses: buffdeveloper/nginx-actions/.github/actions/deleted-files@feat/upgrade
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMON_PATH: 'common'
          ENV_PATH: 'env'
          REPO_PATH: 'nginx-action'

      - name: List deleted files
        run: |
          ls -l nginx-action/files_with_changes
        shell: bash        

      - name: Create KinD cluster
        uses: helm/kind-action@v1.10.0
      
      - name: Test cluster
        run: |
          kubectl cluster-info
          kubectl get nodes
          kubectl get pods --all-namespaces
        shell: bash


      - name: Install NGINX Helm chart
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm install nginx-test-release bitnami/nginx -n nginx-action --create-namespace
        # Replace my-nginx-release and my-namespace with your desired values

      - name: Wait for NGINX deployment to be ready
        run: |
          kubectl wait --for=condition=Available deployment/nginx-test-release -n nginx-action
        # Replace my-nginx-release and my-namespace with the values you used in the Helm install step

