name: Deploy NGINX Helm Chart with Quarkus Build

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v2.1.0

      - name: Create KinD cluster
        uses: helm/kind-action@v1.8.0

      - name: Test cluster
        uses: rethab/bash-action@v1
        with:
          args: |
            kubectl cluster-info
            kubectl get nodes

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        shell: bash

      - name: Install NGINX Helm chart
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm install nginx-test-release bitnami/nginx -n action-space --create-namespace
        # Replace my-nginx-release and my-namespace with your desired values

      - name: Wait for NGINX deployment to be ready
        run: |
          kubectl wait --for=condition=Available deployment/nginx-test-release -n action-space
        # Replace my-nginx-release and my-namespace with the values you used in the Helm install step

